In [1]:
import numpy as np

## An intro to Monte Carlo

* Cleverly sample from a distribution to simulate the workings of a system


We will approximate this integral below:

$$ I = \int_{0}^{\infty}\frac{\exp^{-x}}{1+(x-1)^2}dx $$

Theorem to find average of a function:  
$$ f_{ave} = \frac{1}{b-a}\int_{a}^{b}f(x)dx $$  

Monte Carlo trick --> instead of evaluate integral, estimate average of integrand and use to approximate integral, evaluate (sample) randomly and average the results

In [2]:
x_start = 0
x_end = 2
num_points = 20
x = np.random.uniform(x_start,x_end,num_points)
x

array([0.69233859, 1.08318458, 1.49385128, 0.36206496, 1.66227535,
       0.2833777 , 0.35072119, 1.77114232, 0.06058229, 0.41902143,
       0.46789819, 0.76346699, 0.22468617, 0.94006748, 1.88589859,
       0.46983156, 1.98492194, 0.64269993, 0.62612163, 0.94259539])

In [3]:
func_y = lambda x: 2*x
vectorized_func_y = np.vectorize(func_y)
output = vectorized_func_y(x)
output

array([1.38467718, 2.16636916, 2.98770255, 0.72412993, 3.3245507 ,
       0.5667554 , 0.70144239, 3.54228464, 0.12116457, 0.83804287,
       0.93579637, 1.52693398, 0.44937234, 1.88013496, 3.77179717,
       0.93966312, 3.96984387, 1.28539987, 1.25224326, 1.88519078])

In [4]:
np.average(output)

1.7126747552720682

In [5]:
## Useful Functions
def get_random_interval(x_min, x_max, num_points):
    return np.random.uniform(x_min,x_max,num_points)

In [6]:
get_random_interval(0,10,3)

array([5.24795584, 2.80192496, 9.78025283])

In [7]:
def get_random_number(x_min, x_max):
    return np.random.uniform(x_min,x_max,1)[0]

In [8]:
get_random_number(0,1000)

494.5577490774752

In [9]:
## Function to integrate
def eval_integrand(x):
    func_y = lambda x: np.exp(-x)/(1+(x-1)**2)
    vectorized_func_y = np.vectorize(func_y)
    output = vectorized_func_y(x)
    return output, np.average(output)

In [10]:
eval_integrand(x)

(array([0.45713417, 0.33618946, 0.18048744, 0.49485173, 0.13186827,
        0.4976621 , 0.49535622, 0.10669263, 0.49998061, 0.49171764,
        0.48811589, 0.44135497, 0.49888271, 0.38920349, 0.08499065,
        0.48795411, 0.06973928, 0.4663366 , 0.46908968, 0.38833564]),
 0.37379716467694574)

## Crude Monte Carlo Implementation

1. Get random input from the integration range
2. Evaluate integrand
3. Repeat steps 1-2 for as long as you like
4. Determine average of these samples

In [41]:
def crude_mc_expectation(x_min, x_max, num_samp = 10000):
    x = get_random_interval(x_min,x_max, num_samp)
    y, y_average = eval_integrand(x)
    return (x_max - x_min)*y_average

In [42]:
crude_mc_expectation(0,5, 100000)

0.6952598052428294

## Evaluate Variance of Estimations

$$ \sigma^{2}=\langle I^2\rangle-\langle I\rangle^2 $$

In [ ]:
def crude_mc_variance(x_min, x_max, num_samp = 10000):
    x = get_random_interval(x_min,x_max, num_samp)
    y, y_average = eval_integrand(x)
    return sum_sqs - sq_avg

In [269]:
import pandas as pd

In [288]:
x = np.linspace(0,10,20)
x

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [289]:
y=2*x
y

array([ 0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
        5.26315789,  6.31578947,  7.36842105,  8.42105263,  9.47368421,
       10.52631579, 11.57894737, 12.63157895, 13.68421053, 14.73684211,
       15.78947368, 16.84210526, 17.89473684, 18.94736842, 20.        ])

x          y
0    0.000000   0.000000
1    0.526316   1.052632
2    1.052632   2.105263
3    1.578947   3.157895
4    2.105263   4.210526
5    2.631579   5.263158
6    3.157895   6.315789
7    3.684211   7.368421
8    4.210526   8.421053
9    4.736842   9.473684
10   5.263158  10.526316
11   5.789474  11.578947
12   6.315789  12.631579
13   6.842105  13.684211
14   7.368421  14.736842
15   7.894737  15.789474
16   8.421053  16.842105
17   8.947368  17.894737
18   9.473684  18.947368
19  10.000000  20.000000

In [291]:
tabela = pd.DataFrame(data={"x":x, "y":y})
select = random.randint(0,len(tabela))
tabela.loc[select]['x']
tabela.loc[select]['y']

7

3.6842105263157894

7.368421052631579

## Sources
[1. Towards DS Post - First](https://towardsdatascience.com/monte-carlo-simulations-with-python-part-1-f5627b7d60b0)  
[2. Latex reference](https://www.overleaf.com/learn/latex/Integrals,_sums_and_limits#Sums_and_products)  
[3. Importance Sampling 1](https://github.com/pat-hanbury/MonteCarloTutorial/blob/master/MonteCarloExample.ipynb) [4. Importance Sampling 2](https://github.com/idiap/importance-sampling)  